---
- name: Consultar VMs en mi vcenter.
  hosts: localhost
  gather_facts: false
  vars: 
    - vcenter_hostname: vcenter.gbmcoelab.com
    - vmware_data: SabanaLab
  tasks: 

    - name: Llamda de actualizar vmware tools
      include_tasks: 
        file: tasks/actualiza_vmware_tools.yml
      loop:
        - caprhelserv01
        - caprhelserv02
        - caprhelserv03
        - caprhelserv04
        - caprhelserv05
        - capwinserv01
        - capwinserv02
        - capwinserv03
        - capwinserv04
        - capwinserv05
      loop_control:
        loop_var: servidor
