collections:
  - name: community.windows
    source: https://galaxy.ansible.com

  - name: community.general
    source: https://galaxy.ansible.com

  - name: ansible.windows
    source: https://galaxy.ansible.com
    
  - name: banistmo.demo
    source: https://aapnodehub.idm.gbmcoelab.com/api/galaxy/