---
- name: Housekeeping snapshopts mayores a 3 días
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/main.yml
  tasks:

    - name: Obtener las maquinas virtuales del vcenter.
      community.vmware.vmware_vm_info:
        hostname: '{{ vcenter_hostname }}'
      register: vm_info

    - name: Obtener informacion de snaphots.
      include_tasks:
        file: tasks/query_snaps.yml
      loop: "{{ vm_info.virtual_machines }}"
      when: vm_name.guest_name == ""caprhelserv01""
      loop_control:
        loop_var: vm_name