---
- name: Housekeeping snapshopts mayores a 3 días
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/main.yml

  tasks: 

    - name: Uso de modulo de vmware
      community.vmware.vmware_vm_info:
        hostname: '{{ vcenter_hostname }}'
      register: vm_info