---
- name: Housekeeping snapshopts mayores a 3 días
  hosts: localhost
  gather_facts: false
  vars: 
    - vcenter_hostname: vcenter.gbmcoelab.com
    - vmware_data: SabanaLab

  tasks: 
    - name: Uso de modulo de vmware
      community.vmware.vmware_vm_info:
        hostname: '{{ vcenter_hostname }}'
      register: vm_info

    - name: Obtener informacion de snaphots.
      include_tasks:
        file: tasks/query_snap.yml
      loop: "{{ vm_info.virtual_machines }}"
      loop_control:
        loop_var: vm_name