---
- name: Playbook para trabajar con archivos
  hosts: all
  tasks:

    - name: Copiar el archivo datos.txt a la ruta C:\temp
      ansible.windows.win_copy:
        src: datos.txt
        dest: C:\temp\archivo.txt