---
- name: Playbook que cree un archivo en C:\temp y que ejecute para el grupo correspondiente
  hosts: all
  tasks:

    - name: Busca los datos de los servidores para generar el reporte
      community.windows.win_lineinfile:
        path: C:\Temp\Reporte_{{ ansible_date_time.date }}.csv
        line: "{{ ansible_hostname }} {{ ansible_processor_count }} {{ ansible_memtotal_mb }}"