---
- name: Playbook que cree un archivo en C:\temp y que ejecute para el grupo correspondiente
  hosts: all
  tasks:

    - name: Crear encabezados
      community.windows.win_lineinfile:
        path: C:\Temp\Reporte_{{ ansible_date_time.date }}_v2.csv
        create: true
        line: Servidor Cantidad de CPUs Cantidad de Memoria RAM
      delegate_to: capwinserv02
      run_once: yes

    - name: Reporte de Servidores en Grupo Windows
      community.windows.win_lineinfile:
        path: C:\Temp\Reporte_{{ ansible_date_time.date }}_v2.csv
        line: "{{ ansible_hostname }} {{ ansible_processor_count }} {{ ansible_memtotal_mb }}"
      delegate_to: capwinserv02