- name: Extrar dato de fecha de snapshot. 
  set_fact:
    fecha_snapshot: "{{ snapshots.creation_time }}"

- name: Crear archivo script de fecha en localhost.
  template:
    src: templates/comparar_fechas.sh.j2
    dest: /tmp/comparar_fechas.sh
    mode: '0755'

- name: Ejecutar script y obtener resultado.
  command: /tmp/comparar_fechas.sh
  register: resultado_script

- name: Imprimir resultado para validar el archivo
  debug:
    msg: "El resultado {{ vm_name.guest_name }},{{ snapshots.description }},{{ fecha_snapshot | quote }}"

- name: Agregar linea de snapshot al archivo en caso de eliminar.
  lineinfile:
    path: /tmp/report.csv
    line: "{{ vm_name.guest_name }},{{ snapshots.description }},{{ fecha_snapshot | quote }}"
    create: yes
  when: resultado_script.stdout == "ELIMINAR" and snapshots.description != "NO_BORRAR"

- name: Mostrar resultado en caso de eliminar. 
  debug:
    msg: "El snapshot {{ snapshots.name }} de la maquina {{ nombre_maquina }} es mayor a 3 dias y se eliminara."
  when: resultado_script.stdout == "ELIMINAR" and snapshots.description != "NO_BORRAR"

- name: Eliminar snapshot.
  vmware_guest_snapshot:
    hostname: "{{ vcenter_hostname }}"
    validate_certs: no
    datacenter: "{{ datacenter_name }}"
    name: "{{ vm_name.guest_name }}"
    state: absent
    snapshot_name: "{{ snapshots.name }}"
    folder: ""
  when: resultado_script.stdout == "ELIMINAR" and snapshots.description != "NO_BORRAR"

- name: Mostrar resultado en caso de conservar. 
  debug:
    msg: "El snapshot {{ snapshots.name }} de la maquina {{ nombre_maquina }} es menor a 3 dias y se debe conservar."
  when: resultado_script.stdout == "CONSERVAR"