---
- name: Playbook para instalar httpd
  hosts: all
  tasks:

    - name: Install the latest version of Apache and MariaDB
      ansible.builtin.package:
      name:
       - httpd
      state: latest

    - name: Copia el archivo index.html a la ruta /var/www/
      ansible.builtin.copy:
        src: files/index.html
        dest: /var/www/index.html
        owner: apache
        group: apache
        mode: '0644'