---
- name: Playbook para instalar httpd
  hosts: all
  tasks:

    - name: Install the latest version of Apache
      ansible.builtin.dnf:
      name:
        - httpd
      state: latest

    - name: Copia el archivo index.html a la ruta /var/www/
      ansible.builtin.copy:
        src: files/index.html
        dest: /var/www/index.html
        owner: root
        group: root
        mode: '0644'