---
- name: Copy index.html to remote server
  hosts: all
  become: yes  # Use this if you need elevated privileges
  tasks:
    - name: Copy index.html to C:\inetpub\www\
      ansible.builtin.copy:
        src: C:\temp\index.html  # Path to the file on your local machine
        dest: C:\inetpub\www\index.html  # Destination path on the remote server