---
- name: Playbook que utilice un template variables en vars/vars.yml
  hosts: all
  tasks:

    - name: Uso de template de jinja2
      ansible.builtin.template:
        src: reporte.csv.j2
        dest: "/tmp/archivo.csv"
        owner: root
        group: root
        mode: '0644'
      delegate_to: localhost
   
    - name: Modulo de envío de correo
      mail:
        host: "{{ correo_servidor }}"
        port: "{{ port_servidor }}"
        username: "{{ user_mailserver }}"
        password: "{{ passwd_mailserver }}"
        to: "{{ correo_to }}"
        from: "{{ correo_from }}"
        subject: "Ansible-Report"
        body: |
          Prueba de envío de información por mail. Fecha: {{ ansible_date_time.date }}.
          Bye
        attach:
         - /tmp/archivo.csv
      delegate_to: localhost