---
- name: Obtener nombre del servidor y validar servicio httpd
  hosts: all
  gather_facts: no
  tasks:
    - name: Obtener nombre del servidor
      command: hostname
      register: resultado_hostname
      delegate_to: caprhelserv02

    - name: Start service httpd, if not started
      ansible.builtin.service:
      name: httpd
      register: estado_servicio
      delegate_to: caprhelserv02

    - name: Definir variables para la plantilla
      set_fact:
        nombre_servidor: "{{ resultado_hostname.stdout }}"
        estado_httpd: "{{ estado_servicio.exists }}"
      delegate_to: caprhelserv02

    - name: Generar archivo CSV desde plantilla
      template:
        src: reporte.csv.j2
        dest: /tmp/reporteNameServerAndService.csv
      delegate_to: caprhelserv02

    - name: Mostrar contenido generado
      debug:
        msg: "Servidr: {{ nombre_servidor }} - HTTPD: {{ estado_httpd }}"
      delegate_to: caprhelserv02
