---
- name: Instalar Apache HTTPD y copiar index.html
  hosts: servidores_linux
  become: yes
  vars:
    ruta_web: /var/www/html/index.html

  tasks:
    - name: Instalar Apache HTTPD
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Iniciar y habilitar el servicio httpd
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

    - name: Copiar archivo index.html al directorio web
      ansible.builtin.copy:
        src: files/index.html
        dest: "{{ ruta_web }}"
        owner: apache
        group: apache
        mode: '0644'
