---
- name: Reporte de servicios Windows y envío por correo
  hosts: all
  vars:
    ruta_reporte: "C:\\Temp\\reporte_servicios_{{ ansible_hostname }}.txt"
   
  tasks:

    - name: Obtener servicios en estado Running y Stopped
      win_shell: |
        Get-Service | Select-Object Name, Status | ConvertTo-Json -Depth 2
      register: servicios_json

    - name: Crear contenido del reporte
      set_fact:
        reporte_servicios: |
          Servicios en estado RUNNING:
          {% for svc in servicios_json.stdout | from_json if svc.Status == 'Running' %}
          - {{ svc.Name }}
          {% endfor %}

          Servicios en estado STOPPED:
          {% for svc in servicios_json.stdout | from_json if svc.Status == 'Stopped' %}
          - {{ svc.Name }}
          {% endfor %}

    - name: Guardar reporte en C:\Temp
      win_copy:
        content: "{{ reporte_servicios }}"
        dest: "{{ ruta_reporte }}"
       
    - name: Enviar reporte por correo
      delegate_to: localhost
      community.general.mail:
        host: "{{ mail_server }}"
        port: "{{ port_server }}"
        username: "{{ user_mailserver | default(omit) }}"
        password: "{{ passwd_mailserver | default(omit) }}"
        to: "{{ destinatarios }}"
        from: "{{ mail_from }}"
        subject: "Reporte de Servicios Windows"
        body: |
          Estimado equipo,

          Adjunto el reporte de servicios del servidor.

          Saludos,
          Automatización Ansible
        attach:
          - "{{ ruta_reporte }}"
