---
- name: Reporte de servicios Windows en capwinserv04
  hosts: capwinserv04
  gather_facts: no
  tasks:

    - name: Obtener nombre del servidor
      win_shell: |
        $env:COMPUTERNAME
      register: nombre_servidor

    - name: Obtener servicios en estado Running y Stopped
      win_shell: |
        Get-Service | Select-Object Name, Status | ConvertTo-Json -Depth 2
      register: servicios_json

    - name: Crear contenido del reporte
      set_fact:
        reporte_servicios: |
          Servicios en estado RUNNING:
          {% for svc in servicios_json.stdout | from_json if svc.Status == 'Running' %}
          - {{ svc.Name }}
          {% endfor %}

          Servicios en estado STOPPED:
          {% for svc in servicios_json.stdout | from_json if svc.Status == 'Stopped' %}
          - {{ svc.Name }}
          {% endfor %}

    - name: Guardar reporte en C:\Temp
      win_copy:
        content: "{{ reporte_servicios }}"
        dest: "C:\\Temp\\reporte_servicios_{{ nombre_servidor.stdout }}.txt"
