---
- name: Reporte de servicios Windows y envío por correo
  hosts: capwinserv04
  gather_facts: no
  vars:
    ruta_reporte: "C:\\Temp\\reporte_servicios_{{ ansible_hostname }}.txt"
    correo_destino: "guillermo.palacios@tucorreo.com"  # <-- Actualiza con tu correo real
    servidor_smtp: "smtp.tudominio.com"                # <-- Actualiza con tu servidor SMTP
    mail_from: "reportes@tudominio.com"                # <-- Correo del remitente
    port_server: 25                                     # <-- Puerto SMTP (ajusta si usas TLS/SSL)
    destinatarios: "guillermo.palacios@tucorreo.com"    # <-- Puedes usar lista separada por comas

  tasks:

    - name: Obtener servicios en estado Running y Stopped
      win_shell: |
        Get-Service | Select-Object Name, Status | ConvertTo-Json -Depth 2
      register: servicios_json

    - name: Crear contenido del reporte
      set_fact:
        reporte_servicios: |
          Servicios en estado RUNNING:
          {% for svc in servicios_json.stdout | from_json if svc.Status == 'Running' %}
          - {{ svc.Name }}
          {% endfor %}

          Servicios en estado STOPPED:
          {% for svc in servicios_json.stdout | from_json if svc.Status == 'Stopped' %}
          - {{ svc.Name }}
          {% endfor %}

    - name: Guardar reporte en C:\Temp
      win_copy:
        content: "{{ reporte_servicios }}"
        dest: "{{ ruta_reporte }}"

    - name: Enviar reporte por correo
      community.general.mail:
        host: "{{ servidor_smtp }}"
        port: "{{ port_server }}"
        to: "{{ destinatarios }}"
        from: "{{ mail_from }}"
        subject: "Reporte de Servicios Windows - {{ ansible_hostname }}"
        body: |
          Estimado equipo,

          Adjunto el reporte de servicios del servidor {{ ansible_hostname }}.

          Saludos,
          Automatización Ansible
        attach:
          - "{{ ruta_reporte }}"
