---
- name: Demo de handlers
  hosts: all
  tasks: 

    - name: instalar servicio mariadb 
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: latest
      notify: Levantar servicio en caso de emergencia
      when: ansible_os_family == "RedHat"
      loop: 
        - mariadb
        - httpd

    - name: desinstalar servicio mariadb
      ansible.builtin.dnf:
        name: mariadb
        state: absent

  handlers:
    - name: Levantar servicio en caso de emergencia
      service:
        name: httpd
        state: started