---
- name: Plabook para demostracoin de codigo en CLI.
  hosts: all
  gather_facts: false
  vars_files:
    - vars.yml
  vars: 
    sistema: "Linux"
  tasks:

    - name: Obtener nombre de servidor.
      ansible.builtin.shell: hostname
      register: result_comando

    - name: Imprimir en pantalla
      debug:
        msg: "Nombre: {{ item.nombre }} apellido:{{ item.apellido }}  Servidor: {{ result_comando.stdout }}"
      loop: "{{ usuarios }}"
      when: sistema == "Linux" 

    # - name: Llamar a un playbook
    #   ansible.builtin.include_tasks: holaplaybook.yml
