---
- name: Demo de handlers
  hosts: all
  tasks: 

    - name: instalar servicio httpd 
      ansible.builtin.dnf:
        name: mariadb
        state: latest
      notify: Levantar servicio en caso de emergencia

  handlers:
    - name: Levantar servicio en caso de emergencia
      service:
        name: httpd
        state: started