---
- name: Plabook para demostracoin de codigo en CLI.
  hosts: all
  tasks:

    - name: Obtener nombre de servidor.
      ansible.builtin.shell: hostname
      register: result_comando

    - name: Imprimir en pantalla
      debug:
        msg: "{{ result_comando.stdout }}"

    - name: Llamar a un playbook
      ansible.builtin.include_tasks: holaplaybook.yml
