---
- name: Plabook para demostracoin de codigo en CLI.
  hosts: all
  tasks:

    - name: Obtener nombre de servidor.
      ansible.builtin.shell: hostname
      register: result_comando

    - name: Imprimir en pantalla
      debug:
        msg: "Nombre: {{ nombre }} apellido:{{ apellido }}  Servidor: {{ result_comando.stdout }}"

    # - name: Llamar a un playbook
    #   ansible.builtin.include_tasks: holaplaybook.yml
