---
- name: Plabook para demostracoin de codigo en CLI.
  hosts: all
  #gather_facts: false
  vars_files:
    - vars/vars.yml
  vars: 
    sistema: "Linux"
  tasks:

    - name: Obtener nombre de servidor.
      ansible.builtin.shell: date
      register: result_comando
      when: ansible_os_family == "RedHat"

    - name: Uso de template
      ansible.builtin.template:
        src: templates/reporte.csv.j2
        dest: /tmp/reporte.csv
        owner: root
        group: root
        mode: '0644'
      when: ansible_os_family == "RedHat"

    - name: Imprimir en pantalla
      vars: 
        sistema: "Windows"
      debug:
        msg: "Nombre: {{ item.nombre }} apellido:{{ item.apellido }}  Servidor: {{ result_comando.stdout }}"
      loop: "{{ usuarios }}"
      when: "'ERROR' in result_comando.stdout"


    # - name: Llamar a un playbook
    #   ansible.builtin.include_tasks: holaplaybook.yml
