---
- name: Plabook para demostracoin de codigo en CLI.
  hosts: all
  #gather_facts: false
  vars_files:
    - vars.yml
  vars: 
    sistema: "Linux"
  tasks:

    - name: Obtener nombre de servidor.
      ansible.builtin.shell: hostname
      register: result_comando
      when: ansible_os_family == "RedHat"

    - name: Imprimir en pantalla
      vars: 
        sistema: "Windows"
      debug:
        msg: "Nombre: {{ item.nombre }} apellido:{{ item.apellido }}  Servidor: {{ result_comando.stdout }}"
      loop: "{{ usuarios }}"
      when: item.nombre == "Cesar" and ansible_os_family == "RedHat"

    # - name: Llamar a un playbook
    #   ansible.builtin.include_tasks: holaplaybook.yml
