---
- name: Playbook para windows
  hosts: all
  tasks: 

    - name: Bajar servicio Spooler.
      win_service:
        name: Spooler
        state: stopped
      when: ansible_os_family == "Windows"