---
- name: Playbook para eliminar snapshots mayores a 3 dias.
  hosts: localhost
  gather_facts: true
  vars_files:
    - vars/main.yml
  tasks:

    - name: Obtener las maquinas virtuales del vcenter.
      community.vmware.vmware_vm_info:
        hostname: '{{ vcenter_hostname }}'
      register: vm_info

    - name: Crear archivo de reporte con encabezado.
      copy:
        src: files/reporte.csv
        dest: /tmp/reporte.csv
        mode: '0644'
        
    - name: Recorrido para obtener informacion de snaphots.
      include_tasks:
        file: tasks/consulta_snapshots.yml
      loop: "{{ vm_info.virtual_machines }}"
      when: vm_name.guest_name is defined and vm_name.guest_name is search("rhel")
      loop_control:
        loop_var: vm_name
    
    - name: imprimir archivo de reporte.
      command: cat /tmp/reporte.csv
      register: resultado_reporte

        