---
- name: Plabook para copiar archivo variable
  hosts: all
  tasks:

    - name: Imprimir variable ansible_os_family
	    ansible.builtin.copy
        src: archivo.txt
        dest: /tmp/archivo.txt
        owner: root
        group: root
        mode: '0644'