---
- name: Consultar VMs en mi vcenter.
  hosts: localhost
  gather_facts: false
  vars: 
    - vcenter_hostname: vcenter.gbmcoelab.com
    - vmware_data: SabanaLab
  tasks: 

    - name: Gather one specific VM
      community.vmware.vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        datacenter: "{{ vmware_data }}"
        name: "{{ item }}"
        validate_certs: no
      register: vm_info
      loop:
        - caprhelserv01
        - caprhelserv02
        - caprhelserv03
        - caprhelserv04
        - caprhelserv05
        - capwinserv01
        - capwinserv02
        - capwinserv03
        - capwinserv04
        - capwinserv05
    
